### ISSUE TITLE
Issue - Disconnected From Server

### ISSUE THREAD

**Issue by surabhimitra** [tcpd/lokdhaba#10]
Step 1 - Open the Lok Dhaba website and choose AE tab
Step 2 - Then choose any of the following states ( “Andaman and Nicobar”, “Goa, Daman and Diu” , “Chandigarh”, “Dadra and Nagar Haveli”, “Daman and Diu”, “Lakshadweep” ).
Step 3 - From the Visualization type drop down list, pick any option. Then the screen displays the following "disconnected from server". There is a option to reload the page. On doing so, it takes us to the home page.
![image](https://cloud.githubusercontent.com/assets/26666903/24320345/7ee61e74-1159-11e7-861a-73208db98702.png)

**Comment by hangal** [comment]
This is a general problem, not related to a particular state.

**Comment by hangal** [comment]
repeat of #6, closing.
