### ISSUE TITLE
Visualisation error - Legend overlapping with map

### ISSUE THREAD

**Issue by rohitrawat1** [tcpd/lokdhaba#11]
Step 1 - Select AE
Step 2 - Vote share of Party winners: Map
Step 3 - Select any year, let's say 2014. Select a party name.

Map which appears overlaps with the Legend.

![screen shot 2017-03-25 at 12 54 21 pm](https://cloud.githubusercontent.com/assets/26667092/24320390/41abd156-115a-11e7-982a-5346cbbe1ac1.png)

**Comment by hangal** [comment]
Suggest some text to tell users that they can use drag / zoom controls.

**Comment by chinuhub** [comment]
Not fixed yet. It requires looking at leaflet library to display some message at the top right corner.
