### ISSUE TITLE
Key of "Constituency Wise Party Winners" Map has same colours

### ISSUE THREAD

**Issue by yaminiagarwal** [tcpd/lokdhaba#12]
Step 1 - Open Lok Dhaba and then AE tab
Step 2 - Choose any state (Manipur, Maharashtra, Meghalaya, Mizoram, Nagaland, Karnataka, Arunachal Pradesh)
Step 3 - Choose Visualization type "Constituency Wise Party Winners"
Issue- In the legend of the map, two (or more than two) parties are being represented by the same colour.
![image](https://cloud.githubusercontent.com/assets/26666904/24320433/35addd12-115b-11e7-82c5-de40666deccc.png)

**Comment by hangal** [comment]
@yaminiagarwal we verified this, and it seems to be fixed.
Closing it. Please test and re-open it if needed.
