### ISSUE TITLE
Design Of The Graphs 

### ISSUE THREAD

**Issue by surabhimitra** [tcpd/lokdhaba#13]
Step 1 - Go to Lok Dhaba and subsequently the AE tab. 
Step 2 - Choose any state name from the drop down list.
Step 3 - Choose the "Party wise Vote Share Option" and a graph is displayed. Certain designing issues are present with the graph. 
a) the orientation of the graph is improper. 
b) There is no label on the X- axis. 
c) the title of the graph and source is merging. 
This problems persist in both AE and GE tabs. 
![image](https://cloud.githubusercontent.com/assets/26666903/24320458/d32e4a90-115b-11e7-97f2-ff0d9293f696.png)

**Comment by hangal** [comment]
@surabhimitra pls check and close if fixed.
