### ISSUE TITLE
The tabs "Contact Us" and "How to cite us" are not working

### ISSUE THREAD

**Issue by rohitrawat1** [tcpd/lokdhaba#14]
Home page - tab Contact Us - not working
Home Page - tab How to cite us - not working

![screen shot 2017-03-25 at 1 06 51 pm](https://cloud.githubusercontent.com/assets/26667092/24320472/f7263a3e-115b-11e7-888c-bc9195bc37a3.png)

**Comment by chinuhub** [comment]
Fixed.

**Comment by yaminiagarwal** [comment]
Checked. It is working now.
