### ISSUE TITLE
Dropdown in the Analysis: 2017 elections tab for UP and UK

### ISSUE THREAD

**Issue by yaminiagarwal** [tcpd/lokdhaba#18]
Step 1-Go to Analysis: 2017 elections tab
Step2 - Select Uttar Pradesh from the dropdown list
Issue- The entire document is in bold.
Or
Step 2- Select Uttarakhand from the dropdown list
Issue-It does not direct us anywhere.

**Comment by hangal** [comment]
This will be addressed by simply removing the report.

**Comment by yaminiagarwal** [comment]
Yes the tab is removed. I have reviewed the issue and it no longer persists.
