### ISSUE TITLE
Overlapping of the title and the source

### ISSUE THREAD

**Issue by nissabasim** [tcpd/lokdhaba#2]
![newplot 4](https://cloud.githubusercontent.com/assets/26618099/24283740/7ca697d2-108d-11e7-891d-ad2feb8978fc.png)

Unlike this plot, the title of the plot and the source of the data tend to overlap when viewed on the browser

**Comment by chinuhub** [comment]
@nissabasim I have added the fix. Please have a look and comment.

**Comment by hangal** [comment]
@nissabasim pls test and close if fixed.

**Comment by nissabasim** [comment]
Fixed. Thanks!
