### ISSUE TITLE
Error message - Winning margin of party winners: Map

### ISSUE THREAD

**Issue by rohitrawat1** [tcpd/lokdhaba#21]
Step 1 - Select State Name: Madhya Pradesh
Step 2 - Winning margin of Party winners: Map
Error message appears - The error is also there for Nagaland and J&K.

![screen shot 2017-03-25 at 1 26 56 pm](https://cloud.githubusercontent.com/assets/26667092/24320611/c483cc2e-115e-11e7-9bc3-f1f4b246e63b.png)

**Comment by chinuhub** [comment]
Messages in this issue and in #19, #22 and #25  seems to appear non-uniformly.  This need to be checked after fixing issue #6. If it still does not get fixed then we need to look further into them.

**Comment by hangal** [comment]
fixed now.
