### ISSUE TITLE
Error Message: No. of candidates - Madhya Pradesh

### ISSUE THREAD

**Issue by rohitrawat1** [tcpd/lokdhaba#25]
Step 1: Select AE - Madhya Pradesh - Number of candidates: Map
Error message appears.

![screen shot 2017-03-25 at 1 45 43 pm](https://cloud.githubusercontent.com/assets/26667092/24320745/63915f5a-1161-11e7-94fd-2c8322f2f516.png)

**Comment by chinuhub** [comment]
Fixed. The name of the shape file was not following the convention. Therefore the file was not found during the map drawing. Corrected the name by converting 'Con' to 'con.

**Comment by yaminiagarwal** [comment]
Checked. This issue doesn't persist anymore
