### ISSUE TITLE
Error in the "Candidates Who saved their deposits" tab

### ISSUE THREAD

**Issue by yaminiagarwal** [tcpd/lokdhaba#26]
Step 1-Go to Election Data Visualization then AE tab
Step 2- Choose Nagaland, Andhra Pradesh
Step 3- Select the "Candidates Who saved their deposits" tab from the dropdown list
Issue- Display of error:  could not find function "d3radar"
![image](https://cloud.githubusercontent.com/assets/26666904/24320757/a263a62a-1161-11e7-97aa-477a4848d74e.png)

**Comment by chinuhub** [comment]
Fixed. This issue was because of the leftover of radar library.

**Comment by yaminiagarwal** [comment]
Checked this issue and it no longer persists.
