### ISSUE TITLE
Spelling mistake in terms and conditions

### ISSUE THREAD

**Issue by nissabasim** [tcpd/lokdhaba#29]
'The' has been spelt as 'teh'.

The user must include the citation for data they use in the manner indicated through 'How to Cite' information mentioned on the top of this web page. The user must not claim or imply that the Trivedi Centre for Political Data endorses **## teh** user's use of the data or use of the Centre's logo(s) or trademarks(s) in conjunction with the same.

**Comment by surabhimitra** [comment]
@nissabasim - can you please confirm and close the issue.
