### ISSUE TITLE
Data download fixes

### ISSUE THREAD

**Issue by Rajkamalsingh23** [tcpd/lokdhaba#30]
1. We need to remove the red header where we have written " Code Book (Meaning of the variables present in data". Instead of this we can have a simple heading "Variable Names and Description".

2. We need to have a clear all/select all option where the assembly are listed. This is in reference to the left side box where we have "select assembly" written.

3. We need to be able to make from the top part of the page that if we have to download the data we need to select the terms and condition box. However, at this moment it is not so evident. One way to put it would be to have a pop up menu once anyone clicks download button, which can be placed right below the "select assembly" option on the left.

**Comment by chinuhub** [comment]
@Rajkamalsingh23 I have made the changes. Please have a look at the current deployed version

**Comment by Rajkamalsingh23** [comment]
@chinuhub can we not have all assemblies selected by default. It is redundant if the button there is of select all and by default all boxes are checked for assemblies. 

Also, I think the check box of terms and conditions should not be checked by default.

**Comment by chinuhub** [comment]
@Rajkamalsingh23, I changed the behavior of select all as and download button as requested. Please have a look.
