### ISSUE TITLE
Incorrect Seat Share Maps of Bihar AE

### ISSUE THREAD

**Issue by yaminiagarwal** [tcpd/lokdhaba#33]
STEP 1- Open Data Visualization in Election Data tab of Homepage
STEP 2- Select Bihar in the State Tab
STEP 3- Select "Party Wise Seat Share "/ "Vote Share"
The graph displays that no party has a seat share above 20% which is incorrect
![image](https://cloud.githubusercontent.com/assets/26666904/24577723/ade69950-16f0-11e7-85bd-6e268885321c.png)

**Comment by chinuhub** [comment]
@yaminiagarwal Can you please check it now? This issue was realted to the fact that in 2005 there were two elections and we were only using year as x-axis ticks. I updated it to show year(sa_no) as x-axis ticks.

**Comment by yaminiagarwal** [comment]
@chinuhub  Yes it looks like it is resolved.
