### ISSUE TITLE
Issues of White areas and error in "Gender wise party Winners:Map"

### ISSUE THREAD

**Issue by yaminiagarwal** [tcpd/lokdhaba#36]
Step 1- Go to the Data Visualization of Election Data tab on Homepage
Step 2- Select any state (AP,AP,Assam,Delhi,Gujarat,Haryana,J&K,Kerala,Maharashtra,Mizoram,Odisha,Punjab,Rajasthan,Sikkim,West Bengal) and "Gender wise party Winners:Map"
Problem- There are white areas in the map; the legend is not uniform
or
Step 2- Select any state(Madras, Mysore, Goa Daman & Diu, Puducherry) and "Gender wise party Winners:Map"
Problem- Error " Cannot open data source" is displayed

![image](https://cloud.githubusercontent.com/assets/26666904/24579623/6955c182-1716-11e7-84a9-12cb2730584e.png)
![image](https://cloud.githubusercontent.com/assets/26666904/24579625/71996768-1716-11e7-9d5a-34aa638a7686.png)

**Comment by yaminiagarwal** [comment]
Issue of white area is resolved. However, the error message is still present.

**Comment by chinuhub** [comment]
error message "Cannot open data source" problem (for puducherry) is same as in #38 .
