### ISSUE TITLE
Issues of White area and error message in  "Constituency wise party Winners:Map"

### ISSUE THREAD

**Issue by yaminiagarwal** [tcpd/lokdhaba#37]
Step 1- Go to the Data Visualization of Election Data tab on Homepage
Step 2- Select any state (AP,AP,Assam,Delhi,Gujarat,J&K, Kerala, Maharashtra,Mizoram, Nagaland, Odisha,Punjab,Rajasthan, Sikkim,West Bengal) and "Constituency wise party Winners:Map"
Problem- There are white areas in the map; the legend is not uniform
or
Step 2- Select any state(Madras, Mysore, Goa Daman & Diu, Puducherry) and "Constituency wise party Winners:Map"
Problem- Error " Cannot open data source" is displayed
![image](https://cloud.githubusercontent.com/assets/26666904/24597592/600c50b0-1864-11e7-922c-ce5d868dfa92.png)
![image](https://cloud.githubusercontent.com/assets/26666904/24597804/9b4a9bc2-1865-11e7-89f4-a4202c07d685.png)

**Comment by chinuhub** [comment]
white area is resolved. Cannot open data source problem (for puducherry is same as in #38 ).
