### ISSUE TITLE
Log in and registration feature on the Lok Dhaba website

### ISSUE THREAD

**Issue by Rajkamalsingh23** [tcpd/lokdhaba#4]
@chinuhub please use the four pages that we previously had on Lok Dhaba to add login and registration feature on the current Lok Dhaba shiny version.

Let's make it as simple as possible.
1. They should accept the terms and conditions.
2. They should provide their email address and institution name. Although, institution name should not be mandatory.

**Comment by tcpd** [comment]
This is probably too much work. We can probably do Oauth instead, if anything.
I'd assign this low priority.
-S

**Comment by hangal** [comment]
not being planned.
