### ISSUE TITLE
Vote share logic

### ISSUE THREAD

**Issue by Rajkamalsingh23** [tcpd/lokdhaba#41]
For calculating vote share across time we need to have the previous logic; total votes polled for a party/total votes polled in the election.

**Comment by hangal** [comment]
@gilkumar is this still an issue? 
Pls check and let @mohitkharb know.

**Comment by hangal** [comment]
Question is whether vote share is defined as
votes polled by party/valid votes in ACs/PCs contested by that party
or 
votes polled by party/valid votes in all ACs/PCs in that election.

**Comment by gilkumar** [comment]
Vote share is total vote polled by a party (or a candidate) against the total number of votes polled in that election (or in a seat). 

Gilles Verniers
Assistant Professor of Political Science | Ashoka University
Co-Director, Trivedi Centre for Political Data
gilles.verniers@ashoka.edu.in <mailto:gilles.verniers@ashoka.edu.in> | +91 98109 56049 | www.ashoka.edu.in <http://www.ashoka.edu.in/>

**Comment by mohitkharb** [comment]
i have introduced two viz for vote share for assembly elections
1 voteshare(contested seats)
2 voteshare(all seats)
