### ISSUE TITLE
New visualizations

### ISSUE THREAD

**Issue by Rajkamalsingh23** [tcpd/lokdhaba#43]
2 new visualizations are needed.

1. Party-wise vote share (contested). In a stand alone election we should be able to calculate vote share of a party only for the seats that they have contested. 

The other vote share calculation will be called 
Party-wise vote share (total)
This will include vote share for all seats, not just the one the party contested.

2. We need to add a strike rate visualization. The logic for strike rate would be; total seats won/total seats contested. 

These two visualizations should be done for individual elections. In here the parties should be represented on the x-axis.  (NO: we will have the strike rate like vote share for now.
X-axis is time, and there are line charts per party across time.)

This will fix the issue in #41 also.

**Comment by chinuhub** [comment]
I need to check it with the newly designed framework. I hope that it will be easier to create new visualizations there.
