### ISSUE TITLE
Guj AE primary data changes

### ISSUE THREAD

**Issue by hangal** [tcpd/lokdhaba#51]
From Gilles:
constituency <ANAND> is spelt as <ANAD> for 1967. 
Same remark as earlier, for <SANAD> and <SANAND>

**Comment by Sudesh-Prakash-Singh** [comment]
Fixed.
ANAD -> ANAND
SANAD -> SANAND
I have pushed the updated file to git repository. Please verify.

**Comment by hangal** [comment]
Sudesh why is git show 9f11d9f6328d6d8f5a1b1f7bf2210ab77e9e3740
showing so many lines?
The ECO should change only the issue listed here, and nothing else.

**Comment by Sudesh-Prakash-Singh** [comment]
@hangal That's correct. I have only fixed the listed issue. The log is just a bit descriptive, stating what was changed and where.

**Comment by hangal** [comment]
Try running the above command and see how many lines have changed.
Only the relevant lines should have changed, nothing else!

**Comment by Sudesh-Prakash-Singh** [comment]
Fixed Now.

**Comment by hangal** [comment]
data issue. moved to tcpd_data, not lokdhaba.
