### ISSUE TITLE
Party colors not getting set in GE 

### ISSUE THREAD

**Issue by hangal** [tcpd/lokdhaba#54]
See image below.
Seems to work for AE, but not for GE.
Should be a quick fix, @chinuhub can you pls advise.

**Comment by hangal** [comment]
In GE party-wise winners map, multiple parties get mapped with the same color, which makes the map useless. Suggest, we sort the parties by #seats, and have only the top-10 checked. The remaining parties can be there, but unchecked, so interested users can still have access to them.

**Comment by hangal** [comment]
Not working for AE either.
See 2014, Andhra Pradesh.

![image](https://user-images.githubusercontent.com/1018175/33992713-ad030fae-e0f9-11e7-9be8-532bfb70d29f.png)

**Comment by hangal** [comment]
@mohitkharb will fix it tonight.
@nissabasim and ELM students, please test this thoroughly.

**Comment by mohitkharb** [comment]
updated, please test
