### ISSUE TITLE
Nightly consistency checks

### ISSUE THREAD

**Issue by hangal** [tcpd/lokdhaba#56]
There should be a script that runs every night on all states and GE data. Here are the steps:

a) checks out a fresh copy of the master branch of tcpd_data
b) runs consistency checks, which write out files with the results. Empty files indicate that the consistency check was run, but no problem was noticed.
c) compares consistency checks with "Golden output". This file is generated by running the checks on a known good version of the file.
d) Emails out a report to Mohit and me -- either there were no differences in the consistency checks from the golden version, or there were, and it can list the differences.
e) Over time, we will attempt to make the consistency checks to be as small as possible, or we will eliminate them altogether.

**Comment by mohitkharb** [comment]
Done and Nightly files are getting generated in /home/ashoka/tcpd_data_consistency/ folder in "tcpd.ashoka.edu.in" server, with diff file being mailed every night 12 am to sudheendra and me.
