### ISSUE TITLE
LD code to be updated based on new column names in data files 

### ISSUE THREAD

**Issue by hangal** [tcpd/lokdhaba#58]
see eco#9 in tcpd-data project. (Revamping column names)

**Comment by hangal** [comment]
All scripts and tools and derived files need to be updated including:
- Surf
- mastersheets
- data download screen in LD
- CLEA generation script
- other scripts.

@gilkumar any others?

**Comment by gilkumar** [comment]
None that I can think of right now. 

Gilles Verniers
Assistant Professor of Political Science | Ashoka University
Co-Director, Trivedi Centre for Political Data
gilles.verniers@ashoka.edu.in <mailto:gilles.verniers@ashoka.edu.in> | +91 98109 56049 | www.ashoka.edu.in <http://www.ashoka.edu.in/>
