### ISSUE TITLE
LokDhaba url on TCPD website doesn't redirect to Lokdhaba home page.

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/lokdhaba#59]
LokDhaba url on TCPD website doesn't redirect to Lokdhaba home page.
![screenshot from 2017-09-06 18-45-45](https://user-images.githubusercontent.com/19662760/30113852-afadfffc-9333-11e7-9e3a-4a400e324bb0.png)

**Comment by Sudesh-Prakash-Singh** [comment]
@mohitkharb Alternatively, can we resolve the url to redirect it to the appropriate page?

**Comment by hangal** [comment]
I had put a forward just yesterday -- what happened?!

**Comment by Sudesh-Prakash-Singh** [comment]
Test pass
