### ISSUE TITLE
Infinite loop of "Disconnected from server" messages

### ISSUE THREAD

**Issue by hangal** [tcpd/lokdhaba#62]
Keep getting an infinite loop of this screen, it fades in and out with this message.

![screen shot 2017-10-05 at 6 56 38 am](https://user-images.githubusercontent.com/1018175/31207219-8dcbde54-a99a-11e7-8b8d-40006f78f05a.png)

**Comment by chinuhub** [comment]
@mohitkharb Please look at #32 to solve this issue.

**Comment by mohitkharb** [comment]
It seems that the column name for HP shapefile is "Assembly_N" instead of "Assembly" as in other State assembly files. 
I am working on making same variable names in all state assembly files.
