### ISSUE TITLE
NOTA Turnout: MP 

### ISSUE THREAD

**Issue by nissabasim** [tcpd/lokdhaba#64]
While trying to generate the chart, the drop-down menu for the years doesn't appear. Instead, the interface allows you to write the year manually which I did but even then the map is not generated.

**Comment by hangal** [comment]
@nissabasim does this still happen?

**Comment by nissabasim** [comment]
We discovered that MP can't have a  NOTA map since NOTA  was only introduced in 2014 and the last MP election took place in 2013.

**Comment by hangal** [comment]
Can we give a sensible user message in this case, so the user doesn't get confused?

**Comment by mohitkharb** [comment]
On it, Should I put "Only for post 2013 assemblies, as NOTA was introduced in 2014" ?

**Comment by hangal** [comment]
I think we have to make this message appear any time the NOTA map is not available.

My suggestion would be to not make it specific to this election, but say something like: 
NOTA was not an option in this election.

pls discuss with @gilkumar for exact wording.

**Comment by hangal** [comment]
In fact, ideally, we would write this message in place of the years-dropdown itself. 
"This map is not available for any year."

And the message above would appear in the map area if the user typed in an invalid dropdown.

**Comment by mohitkharb** [comment]
Currently If we select the year in which NOTA was not present, the nota turnout map visualizations will throw an error, so for nota turnout map visualizations, I am passing input years above 2014 only.

**Comment by hangal** [comment]
Can't fix it in time for the Guj results, will do it later.

@gilkumar
