### ISSUE TITLE
Error in browsing lok dhaba

### ISSUE THREAD

**Issue by hangal** [tcpd/lokdhaba#65]
Please see screenshot.

![image](https://user-images.githubusercontent.com/1018175/31892268-3c0ec5e6-b826-11e7-81b7-e8f447609847.png)

**Comment by mohitkharb** [comment]
Its coming fine when I select, maybe its from selecting a range of sequences.
![ld_screenshot](https://user-images.githubusercontent.com/1709862/32156454-83b3f514-bd63-11e7-8681-7c935e1c0a3d.png)

**Comment by mohitkharb** [comment]
This error comes randomly sometimes. Shall we change the priority of this issue? 
cant do much about it as its a pre-built library, and not sure about the origin of error

**Comment by hangal** [comment]
ok, closing now.
