### ISSUE TITLE
Can we have a pop-up message for NOTA? 

### ISSUE THREAD

**Issue by nissabasim** [tcpd/lokdhaba#71]
We should have a message saying that NOTA was only implemented in 2013.

**Comment by mohitkharb** [comment]
mentioned in #64

**Comment by mohitkharb** [comment]
updated
![screenshot from 2018-01-05 16 17 40](https://user-images.githubusercontent.com/1709862/34606260-b915095e-f234-11e7-88d3-dffbed3151d9.png)
