### ISSUE TITLE
Please change fonts to serif.

### ISSUE THREAD

**Issue by hangal** [tcpd/lokdhaba#74]
It looks odd that the text on the page is both in serif and sans-serif.
Suggest changing all fonts to sans-serif.

![image](https://user-images.githubusercontent.com/1018175/33992915-66587368-e0fa-11e7-8b0e-0b7ee2133b6d.png)

**Comment by hangal** [comment]
This is how it should look with all sans-serif.

![image](https://user-images.githubusercontent.com/1018175/33993023-d7e4cf2c-e0fa-11e7-9667-a04060dd56e4.png)

**Comment by hangal** [comment]
We have moved all fonts to serif instead of sans-serif?
Anyway, it's at least consistent now and better than before.
@gilkumar any preferences for serif vs sans?

**Comment by gilkumar** [comment]
My wife says Sans Serif, always. 
I always trust her on fonts issues. 

Gilles 

Gilles Verniers
Assistant Professor of Political Science | Ashoka University
Co-Director, Trivedi Centre for Political Data
gilles.verniers@ashoka.edu.in <mailto:gilles.verniers@ashoka.edu.in> | +91 98109 56049 | www.ashoka.edu.in <http://www.ashoka.edu.in/>

**Comment by mohitkharb** [comment]
The lokdhaba code earlier had 'Droid serif' font, I had made them same everywhere.
I am sorry my knowledge of fonts is week so I could not figure it out, I will resolve this now.

**Comment by hangal** [comment]
Let's go with sans-serif. HelveticaNeue is generally safe.
please factor it out so it's easy to change across the site at any time.

**Comment by mohitkharb** [comment]
@hangal : I have updated, please check.
