### ISSUE TITLE
Name and order of visualizations

### ISSUE THREAD

**Issue by hangal** [tcpd/lokdhaba#76]
Please note the exact spelling and order of the vis. dropdown:
(@gilkumar pls add comments if you have any)

Chart: Voter turnout
Chart: Party vote share (contested)
Chart: Party vote share (all seats)
Chart: Party seat share
Chart: Parties contested and represented
Chart: Candidates contested / deposit saved

Map: Constituency type
Map: Number of candidates
Map: Voter turnout
Map: Winners by party
Map: Winners by gender
Map: Victory margin
Map: Vote share of winners
Map: Party-wise position
Map: NOTA vote

All heat maps should use the same color palette.
(some variation of blue?)

**Comment by mohitkharb** [comment]
I have updated the dropdown in assembly elections tab

**Comment by hangal** [comment]
Thanks, @mohitkharb .
Please remove the extra space before the colon in each title
e.g. Chart: Voter turnout
instead of 
Chart : Voter turnout

**Comment by hangal** [comment]
Also, GE doesn't have map or chart in front of it.
(the visualizations, and their order and names should be consistent with AE as much as possible)

![image](https://user-images.githubusercontent.com/1018175/34475236-2945c420-efb0-11e7-87a1-6cb90e0a4990.png)

**Comment by gilkumar** [comment]
Yes, 

Also, we should give the possibility to visualise GE data by state. 

Ideally, we would want people to be able to compare GE and AE maps and charts for both types of elections. 

Gilles Verniers
Assistant Professor of Political Science | Ashoka University
Co-Director, Trivedi Centre for Political Data
gilles.verniers@ashoka.edu.in <mailto:gilles.verniers@ashoka.edu.in> | +91 98109 56049 | www.ashoka.edu.in <http://www.ashoka.edu.in/>

**Comment by gilkumar** [comment]
I can’t download the GE data from LokDhaba. Too heavy? 

Gilles Verniers
Assistant Professor of Political Science | Ashoka University
Co-Director, Trivedi Centre for Political Data
gilles.verniers@ashoka.edu.in <mailto:gilles.verniers@ashoka.edu.in> | +91 98109 56049 | www.ashoka.edu.in <http://www.ashoka.edu.in/>

**Comment by mohitkharb** [comment]
I had changed earlier for AE only, will update the same for GE now.
The data downloader is working for GE, there might have been some network problem earlier.

**Comment by mohitkharb** [comment]
updated.

**Comment by hangal** [comment]
@mohitkharb seems like GE still does not have all the maps.
![image](https://user-images.githubusercontent.com/1018175/34663170-682b447e-f47b-11e7-8382-a46ea51fe2f3.png)

$2. It takes a while to load. Can you characterize how many MBs is the download?
We need to put a "Loading" spinner on the map side, otherwise user has no clue what is going on.

$3. Even if uncheck BJP, it remains on the map. (I think it is simply taking too long.)
Might want to show the same spinner as above.

$4. Like in AE, there should be a space before the parens in
BJP(282)

![image](https://user-images.githubusercontent.com/1018175/34663209-b87bf2ac-f47b-11e7-9718-ca4734c22d34.png)

$5. (Relatively Minor): On hover on party abbrev., is it possible to show full party name?
 
$6. We have to do something about colors.
NCP and SP are right next to each other and have the same color.
Is it possible to use hatching or something to get more distinguishable colors on screen? (only if its easy).

![image](https://user-images.githubusercontent.com/1018175/34663263-08e22900-f47c-11e7-963a-efb5d8242063.png)

**Comment by hangal** [comment]
fixed.
